version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # container port:host port
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0 # makes flask reachable from the host
      - FLASK_RUN_PORT=5000 # makes flask listen this port
    volumes:
      - ./backend:/app
    command: flask run